package DSLMachineLearning.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EnumModelFamilyName extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EnumModelFamilyName() {
    super(0xc443d583ed614d79L, 0xbf612b6fba21dfcaL, 0x4c851a0d9d333b9bL, "EnumModelFamilyName", "r:39ccb51b-8655-43ec-9c8e-61b9dee4ce72(DSLMachineLearning.structure)/5513841964559317915");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_classifier_0 = new EnumerationDescriptor.MemberDescriptor("classifier", "CLASSIFIER ", 0x4c851a0d9d333b9cL, "r:39ccb51b-8655-43ec-9c8e-61b9dee4ce72(DSLMachineLearning.structure)/5513841964559317916");
  private final EnumerationDescriptor.MemberDescriptor myMember_regression_0 = new EnumerationDescriptor.MemberDescriptor("regression", "REGRESSION ", 0x4c851a0d9d333ba0L, "r:39ccb51b-8655-43ec-9c8e-61b9dee4ce72(DSLMachineLearning.structure)/5513841964559317920");
  private final EnumerationDescriptor.MemberDescriptor myMember_clustering_0 = new EnumerationDescriptor.MemberDescriptor("clustering", "CLUSTERING", 0x4c851a0d9d333ba4L, "r:39ccb51b-8655-43ec-9c8e-61b9dee4ce72(DSLMachineLearning.structure)/5513841964559317924");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xc443d583ed614d79L, 0xbf612b6fba21dfcaL, 0x4c851a0d9d333b9bL, 0x4c851a0d9d333b9cL, 0x4c851a0d9d333ba0L, 0x4c851a0d9d333ba4L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_classifier_0, myMember_regression_0, myMember_clustering_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_classifier_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "classifier":
        return myMember_classifier_0;
      case "regression":
        return myMember_regression_0;
      case "clustering":
        return myMember_clustering_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
