package DSLMachineLearning.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Document = 0;
  public static final int Input = 1;
  public static final int InputList = 2;
  public static final int InputName = 3;
  public static final int InputType = 4;
  public static final int InputTypeName = 5;
  public static final int Inputs = 6;
  public static final int Layer = 7;
  public static final int LayerList = 8;
  public static final int LayerName = 9;
  public static final int LayerParams = 10;
  public static final int Layers = 11;
  public static final int Model = 12;
  public static final int ModelDescription = 13;
  public static final int ModelFamily = 14;
  public static final int ModelFamilyName = 15;
  public static final int ModelName = 16;
  public static final int ModelType = 17;
  public static final int ModelTypeName = 18;
  public static final int Number = 19;
  public static final int NumberList = 20;
  public static final int Output = 21;
  public static final int OutputList = 22;
  public static final int OutputName = 23;
  public static final int OutputType = 24;
  public static final int OutputTypeName = 25;
  public static final int Outputs = 26;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc443d583ed614d79L, 0xbf612b6fba21dfcaL);
    builder.put(0x4c851a0d9d3322d0L, Document);
    builder.put(0x4c851a0d9d333b3aL, Input);
    builder.put(0x4c851a0d9d333b2aL, InputList);
    builder.put(0x4c851a0d9d333b43L, InputName);
    builder.put(0x4c851a0d9d333b44L, InputType);
    builder.put(0x4c851a0d9d333b49L, InputTypeName);
    builder.put(0x4c851a0d9d333b27L, Inputs);
    builder.put(0x4c851a0d9d333b70L, Layer);
    builder.put(0x4c851a0d9d333b6dL, LayerList);
    builder.put(0x4c851a0d9d333b7bL, LayerName);
    builder.put(0x4c851a0d9d333b7cL, LayerParams);
    builder.put(0x4c851a0d9d333b76L, Layers);
    builder.put(0x4c851a0d9d333b6aL, Model);
    builder.put(0x4c851a0d9d333b26L, ModelDescription);
    builder.put(0x4c851a0d9d333b12L, ModelFamily);
    builder.put(0x3e000331b47276c0L, ModelFamilyName);
    builder.put(0x4c851a0d9d333b0fL, ModelName);
    builder.put(0x4c851a0d9d333b22L, ModelType);
    builder.put(0x4c851a0d9d333b25L, ModelTypeName);
    builder.put(0x4c851a0d9d333b84L, Number);
    builder.put(0x4c851a0d9d333b79L, NumberList);
    builder.put(0x4c851a0d9d333b5fL, Output);
    builder.put(0x4c851a0d9d333b5cL, OutputList);
    builder.put(0x4c851a0d9d333b65L, OutputName);
    builder.put(0x4c851a0d9d333b66L, OutputType);
    builder.put(0x4c851a0d9d333b69L, OutputTypeName);
    builder.put(0x4c851a0d9d333b4bL, Outputs);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
